#ifndef TX_USER_H
#define TX_USER_H

#define TX_TIMER_TICKS_PER_SECOND 1000
#define TX_MAX_PRIORITIES 32
#define TX_TIMER_THREAD_STACK_SIZE 1024
#define TX_TIMER_THREAD_PRIORITY 0
#define TX_ENABLE_STACK_CHECKING

#endif
